spring.datasource.url=jdbc:postgresql://localhost:5432/exam_db
spring.datasource.username=postgres
spring.datasource.password=aiym125140
spring.application.name=end
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
